gui:
  theme:
    selectedLineBgColor:
      - reverse
git:
  branchLogCmd: "git log --color=always --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=iso"
