source /home/danielhabib/dotfiles/nvim/config/options.vim
source /home/danielhabib/dotfiles/nvim/config/gruvbox.vim
source /home/danielhabib/dotfiles/nvim/config/vim-buftabline.vim
source /home/danielhabib/dotfiles/nvim/config/ctrlp.vim
source /home/danielhabib/dotfiles/nvim/config/lightline.vim
source /home/danielhabib/dotfiles/nvim/config/vim-test.vim
source /home/danielhabib/dotfiles/nvim/config/gitsigns.vim
source /home/danielhabib/dotfiles/nvim/config/nerdtree.vim
source /home/danielhabib/dotfiles/nvim/config/vim-fugitive.vim
source /home/danielhabib/dotfiles/nvim/config/telescope.vim
source /home/danielhabib/dotfiles/nvim/config/tagbar.vim
source /home/danielhabib/dotfiles/nvim/config/harpoon.vim
source /home/danielhabib/dotfiles/nvim/config/vim-highlightedyank.vim
source /home/danielhabib/dotfiles/nvim/config/maps.vim
source /home/danielhabib/dotfiles/nvim/config/treesitter.vim
source /home/danielhabib/dotfiles/nvim/config/cmp.vim
source /home/danielhabib/dotfiles/nvim/config/telescope-ui-select.vim
source /home/danielhabib/dotfiles/nvim/config/switch.vim
source /home/danielhabib/dotfiles/nvim/config/easy-align.vim
source /home/danielhabib/dotfiles/nvim/config/calltree.vim
source /home/danielhabib/dotfiles/nvim/config/vcs-jump.vim
nnoremap <leader>s! mmo<ESC>:.!ls -rt /tmp/nvim*/*dbout \| tail -n1 \| xargs cat<CR>`m
