source /home/danielhabib/dotfiles/nvim/config/options.vim
source /home/danielhabib/dotfiles/nvim/config/gruvbox.vim
source /home/danielhabib/dotfiles/nvim/config/vim-buftabline.vim
source /home/danielhabib/dotfiles/nvim/config/ctrlp.vim
source /home/danielhabib/dotfiles/nvim/config/lightline.vim
source /home/danielhabib/dotfiles/nvim/config/vim-test.vim
luafile /home/danielhabib/dotfiles/nvim/config/gitsigns.lua
source /home/danielhabib/dotfiles/nvim/config/nerdtree.vim
source /home/danielhabib/dotfiles/nvim/config/vim-fugitive.vim
source /home/danielhabib/dotfiles/nvim/config/telescope.vim
source /home/danielhabib/dotfiles/nvim/config/tagbar.vim
source /home/danielhabib/dotfiles/nvim/config/harpoon.vim
source /home/danielhabib/dotfiles/nvim/config/vim-highlightedyank.vim
source /home/danielhabib/dotfiles/nvim/config/maps.vim
luafile /home/danielhabib/dotfiles/nvim/config/treesitter.lua
source /home/danielhabib/dotfiles/nvim/config/cmp.vim
source /home/danielhabib/dotfiles/nvim/config/telescope-ui-select.vim
source /home/danielhabib/dotfiles/nvim/config/switch.vim
source /home/danielhabib/dotfiles/nvim/config/easy-align.vim
source /home/danielhabib/dotfiles/nvim/config/calltree.vim
source /home/danielhabib/dotfiles/nvim/config/vcs-jump.vim
luafile /home/danielhabib/dotfiles/nvim/config/mason.lua
luafile /home/danielhabib/dotfiles/nvim/config/oil.lua
